### ISSUE TITLE
Double temperature still shows in the terminal tab

### ISSUE THREAD

**Issue by Cancklehead** [SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix#10]
Although I'm getting great prints, my Ender 3 V2 still seems to be reporting double. I'm getting no more error warnings at startup though.

Just an example-

Recv:   TT::200.00200.00  //200.00200.00  BB::50.0050.00  //50.0050.00  @@::9393  BB@@::2222

**Comment by balthisar** [comment]
I came here to report the same. Actually, the plugin seems to be working on the internal string, which means the "Temperature" tab now works properly, but the "Terminal" tab is still showing the incorrect temperature strings.

It also means "Suppress temperature messages" on that tab doesn't work, so it's incredibly noisy to work with.

I would like to see this plugin work to fix the string there, too, so that I don't have to change the regex in the settings, which is actually what I came here looking for (because I hate figuring out complex regex by myself).

**Comment by balthisar** [comment]
TIL you can just add new filters without overwriting existing ones. In my case, I just added a new, temporary "Suppress buggy temperature messages" filter with the simple regex `(Send: (N\d+\s+)?M105)|(Recv:\s+TT::.*)`

It doesn't solve the issue, but until I get around to making a new Marlin without the bug, it will at least keep my terminal a bit less noisy.

**Comment by Cancklehead** [comment]
Ok, that's good to know I'm not the only one then...
I'll give that a go with the temp filter, thanks for the tip.

**Comment by AlbertMN** [comment]
Just to clarify to anyone else reading this; the plugin works, and does what it's supposed to do, but as the "terminal" tab shows the raw content it gets from the printer, it still look weird in the GCODE terminal, also resulting in the "suppress temperature" feature not working.

I had not thought of the suppress feature, so I'll see what I can do about that :)

**Comment by Cancklehead** [comment]
Ya, that's the title I meant to write, Albert! lol. 
I applied the filter successfully, thanks balthisar.

**Comment by Cancklehead** [comment]
After having to rebuild Octopi, my terminal in Octoprint now shows the temperature normally and I'm able to use "suppress temperature". Thanks for the help.

**Comment by jrichter212** [comment]
> After having to rebuild Octopi, my terminal in Octoprint now shows the temperature normally and I'm able to use "suppress temperature". Thanks for the help.

I'm sorry I do not know much but I am having this same problem with the plugin and I was wondering what you meant by "rebuild octopi"

Thanks.

**Comment by Cancklehead** [comment]
No worries. I had a problem where Octoprint was unresponsive, so I reformatted my sd card for the raspberry pi and reinstalled Octopi. I'm using Creality Temperature (1.2.4) plugin and Creality-2x-temperature-reporting-fix (0.0.4) plugin.
![doubleReportFix](https://user-images.githubusercontent.com/73356792/104548447-1cb5e100-5631-11eb-9e46-df494b891cf7.JPG)
