### ISSUE TITLE
Ender3v2 with BLTouch

### ISSUE THREAD

**Issue by MorfCRD** [SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix#11]
Hi,
Installed the plugin, and still most of the reports are wrong format:
Changing monitoring state from "Starting" to "Printing"
Send: N1 M140 S50*81
Recv: ok
Send: N2 M105*37
Recv: ok T:125.49 /0.00 B:46.28 /50.00 @:0 B@:0
Send: N3 M190 S50*94
Recv:  T:125.49 /0.00 B:46.28 /50.00 @:0 B@:0 W:?
Recv:  T:124.83 /0.00 B:46.25 /50.00 @:0 B@:127 W:?
Recv:   TT::124.72124.72  //0.000.00  BB::46.2846.28  //50.0050.00  @@::00  BB@@::127127
Recv: 
Recv:  T:124.12 /0.00 B:46.32 /50.00 @:0 B@:127 W:?
....
Recv:   TT::141.00141.00  //190.00190.00  BB::50.0050.00  //50.0050.00  @@::127127  BB@@::1616
Recv: 
Recv:  T:141.87 /190.00 B:50.00 /50.00 @:127 B@:16 W:?
Recv: echo:busy: processing
Recv:  T:143.59 /190.00 B:50.00 /50.00 @:127 B@:16 W:?
Recv:   TT::144.71144.71  //190.00190.00  BB::49.9849.98  //50.0050.00  @@::127127  BB@@::2222
Recv: 
Recv:  T:145.25 /190.00 B:50.00 /50.00 @:127 B@:17 W:?

browser.user_agent: Chrome
env.plugins.pi_support.model: Raspberry Pi 3 Model B Plus Rev 1.3
env.plugins.pi_support.octopi_version: 0.17.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 20.3.3
env.python.version: 3.7.3
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.3
printer.firmware: Marlin Ver 1.0.1

Printer FW, official creality:
4.2.2 Ender-3 v2 Marlin2.0.1  BLtouchV1.1.1without adapter board firmware.rar
Name: Ender-3 V2-Marlin-2.0.1 - V1.1.1 - BLTouch(1).bin

**Comment by AlbertMN** [comment]
The plugin doesn't change what it shows in the terminal. The way you can tell it works, is if OctoPrint doesn't say your extruder & bed is 0 degrees :)
