### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-req-build-4GAkw3/

### ISSUE THREAD

**Issue by Bboy486** [SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix#12]
cd OctoPrint
pi@raspberrypi:~/OctoPrint $ sudo pip install "https://github.com/SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip
  Using cached https://github.com/SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip
    Complete output from command python setup.py egg_info:
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-req-build-4GAkw3/
pi@raspberrypi:~/OctoPrint $

**Comment by leder11011** [comment]
Please reopen this ticket:
```
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-req-build-X0FM_J/

```
