### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Cornflix244** [SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix#13]
![image](https://user-images.githubusercontent.com/70451196/113574955-6e14b180-961d-11eb-9d79-718d71289b29.png)

![image](https://user-images.githubusercontent.com/70451196/113576140-4b839800-961f-11eb-9971-d03f50e1468a.png)

The installation is failing with one of these two error messages.

**Comment by AlbertMN** [comment]
How are you trying to install? Looks like you're trying to do it directly on the server, so what exactly is the line you're trying it with if this is the case?

**Comment by Cornflix244** [comment]
> How are you trying to install? Looks like you're trying to do it directly on the server, so what exactly is the line you're trying it with if this is the case?

I put this in while SSH-ing into the Raspi:
`pip install "https://github.com/SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip"`
