### ISSUE TITLE
[BUG] Plugin fix isn't working with CR6 SE

### ISSUE THREAD

**Issue by khanhntran** [SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix#6]
Installed the plugin today to test on my CR6 SE - default firmware (v1.02), but the temperature output did not change.

Things tried:
- Disconnect and reconnect to printer
- Restart Octoprint server
- Reboot the entire Pi

Let me know if you need any logs

**Comment by AlbertMN** [comment]
Hi there. GitHub isn't very good at sending me notifications about issues right now... So sorry for the late reply!

Can you please send me both octoprint.log and serial.log? :)

**Comment by khanhntran** [comment]
Hey, no worries. I want to make sure something before sending over the logs - Is this fix supposed to change the temperature output under the `Terminal` tab on Octoprint so that it can get properly filtered? Or is this only for the temperature readings being sent to the `Temperature` tab on Octoprint?

**Comment by AlbertMN** [comment]
This plugin "intercepts" the GCODE, checks if it has a case of _"double-everything-itis"_ and returns a parsed _(fixed)_ temperature report to OctoPrint. So the output in the terminal should still be weird AFAIK, but the temperature that shows everywhere on the panel should be fixed. A simple screenshot of your terminal, with a temperature reporting _(which is done quite frequently)_, and we can determine whether this plugin will fix your issues or not.

**Comment by khanhntran** [comment]
<img width="1086" alt="Screen Shot 2020-09-23 at 12 04 10 PM" src="https://user-images.githubusercontent.com/15078330/94038844-f83dac80-fd94-11ea-9abf-029afbe6dc8e.png">
Here's a screenshot. This is the terminal output with the plugin installed. I guess what I'm seeing is expected behavior?

**Comment by AlbertMN** [comment]
Yes :) That's the expected behavior.

**Comment by khanhntran** [comment]
Ah, if that's expected then I guess I'll just have to change the filtering regex. Thanks for your insight

**Comment by AlbertMN** [comment]
This plugin should fix this for you - it should have the regex that fixes this. What seems to be the problem? Do you still not see the temperatures reported properly?

**Comment by khanhntran** [comment]
The `suppress temperature messages` toggle isn't filtering
