### ISSUE TITLE
[Thanks] working on V4.2.7

### ISSUE THREAD

**Issue by Chatissimus** [SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix#7]
Hi,

Just to report it's also working  for V4.2.7 mainboard / v1.0.1 firware in my side into a Ender3-pro 
(the new  Ender3/5/-pro 32bit silent board send by creality since end of august)

I assume the "issue" on temperature reporting is present on all new 32bit creality mainboard for ender 3 / 5

Thanks

**Comment by AlbertMN** [comment]
Glad it's working! And that's right - all new 32 bit Creality mainboards seem to be doing this... Also CR-6 SE. Updated the repo and plugin name :)
