### ISSUE TITLE
Error Message When Installing 

### ISSUE THREAD

**Issue by ambcmb** [SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix#9]
I upgraded my Ender 3 V1 to the silent V4.2.7 board. Upon reboot I received the error "Warning: Firmware Broken" that lead me to this fix. When I run the command I receive this error:

pip install "https://github.com/SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip
  Using cached https://github.com/SimplyPrint/OctoPrint-Creality2xTemperatureReportingFix/archive/master.zip
    Complete output from command python setup.py egg_info:
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-req-build-NhrWZH/

**Comment by AlbertMN** [comment]
You're using the wrong `pip` :) You have to use OctoPrint's. Use the plugin manager instead; go to the OctoPrint settings by clicking the wrench in the navbar, go to "Plugin manager", click "Get more" in the bottom and search for "Creality (...)" > click install.

**Comment by ambcmb** [comment]
Thanks. I appreciate it.
